version: '2'
services:
  cowry:
    build:
      context: .
      dockerfile: Dockerfile
    image: cowry:dev
    depends_on:
     - redis
     - etcd
     - mysql
    ports:
     - "2333:2333"
     - "3000:3000"
    volumes:
     - /Users/aong/workspace/git/cowry/server:/cowry/
  worker:
    build:
      context: ./core/components/workers
      dockerfile: Dockerfile
    image: cowry-worker:dev
    depends_on:
     - cowry
    ports:
     - "2334:2334"
    volumes:
     - /Users/aong/workspace/git/cowry/server/certs:/certs
     - /tmp/cowry/data:/data
  backup:
    build:
      context: ./core/components/backup
      dockerfile: Dockerfile
    image: cowry-backup:dev
    depends_on:
      - cowry
    ports:
     - "2200:22"
    environment:
     - SSH_USER=cowry
    volumes:
     - /Users/aong/workspace/git/cowry/server/certs:/certs
     - /tmp/cowry/backup_data:/data
  etcd:
    image: elcolio/etcd
    volumes:
      - "/tmp/cowry/etcd:/data"
  etcd-borwser:
    image: buddho/etcd-browser
    ports:
      - "8000:8000"
    environment:
      - ETCD_HOST=etcd
      - ETCD_PORT=2379
  redis:
    image: redis
    ports:
     - "6379:6379"
  mysql:
    image: mysql
    environment:
      - MYSQL_DATABASE=cowry
      - MYSQL_ROOT_PASSWORD=1234
    volumes:
      - "/tmp/cowry/mysql-data:/var/lib/mysql"
    ports:
      - "3307:3306"
