version: '2'
services:
  cowry:
    build:
      context: .
      dockerfile: Dockerfile
    image: cowry:dev
    depends_on:
     - redis
    ports:
     - "2333:2333"
     - "3000:3000"
    volumes:
     - /tmp/cowry/db:/cowry/db/data
     - /tmp/cowry/certs:/cowry/certs
  worker:
    build:
      context: ./core/components/workers
      dockerfile: Dockerfile
    image: cowry-worker:dev
    depends_on:
     - cowry
    ports:
     - "2334:2334"
    volumes:
     - /tmp/cowry/certs:/certs
     - /tmp/cowry/data:/data
  backup:
    build:
      context: ./core/components/backup
      dockerfile: Dockerfile
    image: cowry-backup:dev
    depends_on:
      - cowry
    ports:
     - "2200:22"
    environment:
     - SSH_USER=cowry
    volumes:
     - /tmp/cowry/certs:/certs
     - /tmp/cowry/backup_data:/data
  redis:
    image: redis
    ports:
     - "6379"
